# Generated by Django 5.1 on 2024-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employersignup',
            name='Confirm_password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='employersignup',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employersignup',
            name='Password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
