# Generated by Django 5.1.1 on 2024-09-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer_app', '0002_employersignup_confirm_password_employersignup_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employersignup',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employersignup',
            old_name='Company_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='employersignup',
            old_name='Confirm_password',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='employersignup',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employersignup',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='employersignup',
            old_name='Phone_no',
            new_name='phone_no',
        ),
    ]
