# Generated by Django 5.1.1 on 2024-09-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer_app', '0003_rename_address_employersignup_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerSignup',
        ),
    ]
